//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace microservice_rest_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int ID { get; set; }
        public System.DateTime StockDate { get; set; }
        public string Symbol { get; set; }
        public string OpenStock { get; set; }
        public string CloseStock { get; set; }
        public string LowStock { get; set; }
        public string HighStock { get; set; }
        public string Volume { get; set; }
    }
}
